package TME2;


/**
* TME2/ServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tme2.idl
* Tuesday, September 23, 2014 6:21:58 o'clock PM EDT
*/

public abstract class ServerPOA extends org.omg.PortableServer.Servant
 implements TME2.ServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerFile", new java.lang.Integer (0));
    _methods.put ("removeFile", new java.lang.Integer (1));
    _methods.put ("findFile", new java.lang.Integer (2));
    _methods.put ("getFile", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TME2/Server/registerFile
       {
         String filename = in.read_string ();
         String clientname = in.read_string ();
         String port = in.read_string ();
         this.registerFile (filename, clientname, port);
         out = $rh.createReply();
         break;
       }

       case 1:  // TME2/Server/removeFile
       {
         String filename = in.read_string ();
         String clientname = in.read_string ();
         this.removeFile (filename, clientname);
         out = $rh.createReply();
         break;
       }

       case 2:  // TME2/Server/findFile
       {
         String filename = in.read_string ();
         boolean $result = false;
         $result = this.findFile (filename);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // TME2/Server/getFile
       {
         String filename = in.read_string ();
         String $result = null;
         $result = this.getFile (filename);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TME2/Server:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Server _this() 
  {
    return ServerHelper.narrow(
    super._this_object());
  }

  public Server _this(org.omg.CORBA.ORB orb) 
  {
    return ServerHelper.narrow(
    super._this_object(orb));
  }


} // class ServerPOA
