package TME2;


/**
* TME2/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tme2.idl
* Tuesday, September 23, 2014 6:21:58 o'clock PM EDT
*/

public interface ServerOperations 
{
  void registerFile (String filename, String clientname, String port);
  void removeFile (String filename, String clientname);
  boolean findFile (String filename);
  String getFile (String filename);
} // interface ServerOperations
